name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ make libgtest-dev dpkg-dev

    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run tests
      run: ./build/tests

    - name: Package into .deb
      run: |
        mkdir -p build/deb/usr/local/bin
        cp build/adapter build/deb/usr/local/bin/adapter
        mkdir -p build/deb/DEBIAN
        cat <<EOF > build/deb/DEBIAN/control
        Package: adapter
        Version: 1.0.0
        Architecture: amd64
        Maintainer: Матвей
        Description: Adapter design pattern implementation
        EOF
        dpkg-deb --build build/deb adapter.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: adapter-package
        path: adapter.deb

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: adapter-package
        path: .

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: adapter.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
