name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ make libgtest-dev dpkg-dev

      - name: Configure and build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run tests
        run: ./build/tests

      - name: Package into .deb
        run: |
          mkdir -p build/deb/usr/local/bin
          cp build/adapter build/deb/usr/local/bin/adapter
          mkdir -p build/deb/DEBIAN
          echo "Package: adapter" > build/deb/DEBIAN/control
          echo "Version: 1.0.0" >> build/deb/DEBIAN/control
          echo "Architecture: amd64" >> build/deb/DEBIAN/control
          echo "Maintainer: Матвей" >> build/deb/DEBIAN/control
          echo "Description: Adapter design pattern implementation" >> build/deb/DEBIAN/control
          dpkg-deb --build build/deb build/adapter.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: adapter-package
          path: build/adapter.deb

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: adapter-package
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          files: adapter.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
