name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List tests directory
        run: ls -l Structural/Adapter/tests

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ make libgtest-dev dpkg-dev

      - name: Configure and build
        run: |
          cmake -S Structural/Adapter -B Structural/Adapter/build
          cmake --build Structural/Adapter/build

      - name: Run tests if available
        run: |
          if [ -f Structural/Adapter/build/tests ]; then
            Structural/Adapter/build/tests
          else
            echo "Tests binary not found, skipping tests run"
          fi

      - name: Package into .deb
        run: |
          mkdir -p build/deb/usr/local/bin
          cp Structural/Adapter/build/adapter build/deb/usr/local/bin/adapter
          mkdir -p build/deb/DEBIAN
          echo "Package: adapter" > build/deb/DEBIAN/control
          echo "Version: 1.0.0" >> build/deb/DEBIAN/control
          echo "Architecture: amd64" >> build/deb/DEBIAN/control
          echo "Maintainer: Матвей" >> build/deb/DEBIAN/control
          echo "Description: Adapter design pattern implementation" >> build/deb/DEBIAN/control
          dpkg-deb --build build/deb adapter.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: adapter-package
          path: adapter.deb

  release:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: adapter-package
          path: .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: adapter.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
